version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.9
    commands:
      - export DOCKERHUB_USER=$(aws secretsmanager get-secret-value --secret-id /creds/dockerhub --query SecretString --output text | jq -r '.DOCKERHUB_USER')
      - export DOCKERHUB_PASS=$(aws secretsmanager get-secret-value --secret-id /creds/dockerhub --query SecretString --output text | jq -r '.DOCKERHUB_PASS')
      - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  pre_build:
    commands:
      - pip install -e "explorer-backend[dev,test]"
      - pytest explorer-backend/test/
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - bin/docker_build.sh
      - docker tag node-explorer:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-explorer:latest
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/node-explorer:latest
      - aws ecs update-service --cluster Mesh-Services --service Node-Explorer-Fargate --force-new-deployment
